---
managedNamespaces: ["sample"]

createClusterScopedResources: true

refs:
  enforceRBAC: true

webhook:
  enabled: true
  namespaceSelector:
    matchExpressions:
      - key: "eck.k8s.elastic.co/tenant"
        operator: In
        values: ["sample"]
