---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: elastic-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filebeat
rules:
- apiGroups:
  - policy
  resourceNames:
  - filebeat
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
    - ""
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: elastic-system

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: filebeat
spec:
  allowedHostPaths:
  - pathPrefix: /var/log/containers
  - pathPrefix: /var/log/pods
  - pathPrefix: /var/lib
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - emptyDir
  - secret
  - downwardAPI
  - configMap
  - persistentVolumeClaim
  - projected
  - hostPath
  hostNetwork: true
