---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elastic
rules:
- apiGroups:
  - policy
  resourceNames:
  - elastic
  resources:
  - podsecuritypolicies
  verbs:
  - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic
subjects:
  - kind: ServiceAccount
    name: elastic-operator
    namespace: elastic-system
  - kind: ServiceAccount
    name: default
    namespace: elastic-system

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: elastic
spec:
  allowPrivilegeEscalation: true
  allowedHostPaths:
  - pathPrefix: /var/log
    readOnly: true
  - pathPrefix: /var/lib/docker/containers
    readOnly: true
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostPorts:
  - max: 65535
    min: 1
  runAsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - hostPath
  - secret
  - downwardAPI
  - persistentVolumeClaim
  hostPID: true
  hostIPC: true
  hostNetwork: true
